import type { Book } from "./types";

export const mockBooks: Book[] = [
  {
    id: "book-001",
    slug: "the-night-library",
    title: "The Night Library",
    author: "Elena Marsh",
    description:
      "After midnight, a forgotten wing of the city library opens only for those who still believe in stories. A quiet, luminous novel about memory, belonging, and the books that choose their readers.",
    priceCents: 2800,
    format: "physical",
    category: "fiction",
    featured: true,
    rating: 4.6,
    reviewCount: 128,
    inventoryCount: 12,
    pages: 320,
    isbn: "978-1-4521-8842-1",
    publisher: "North Lantern Press",
    publishedYear: 2024,
    coverHue: 220,
  },
  {
    id: "book-002",
    slug: "roots-of-stillness",
    title: "Roots of Stillness",
    author: "Jonah Pike",
    description:
      "Essays on walking slowly through forests, deserts, and the edges of towns—written for anyone who needs the world to speak in a softer voice.",
    priceCents: 2200,
    format: "physical",
    category: "nature",
    featured: true,
    rating: 4.4,
    reviewCount: 86,
    inventoryCount: 8,
    pages: 248,
    publisher: "Moss & Field",
    publishedYear: 2023,
    coverHue: 145,
  },
  {
    id: "book-003",
    slug: "ink-and-ember-epub",
    title: "Ink & Ember",
    author: "Amara Sol",
    description:
      "A digital-only collection of interconnected short fiction. Download includes PDF and EPUB. Delivered by email after purchase.",
    priceCents: 1400,
    format: "digital",
    category: "literary",
    featured: true,
    rating: 4.8,
    reviewCount: 214,
    publisher: "Novella Digital",
    publishedYear: 2025,
    coverHue: 12,
  },
  {
    id: "book-004",
    slug: "cartography-of-wonder",
    title: "A Cartography of Wonder",
    author: "Dr. Lina Cho",
    description:
      "Nonfiction that maps how curiosity travels—from childhood museums to research labs—with elegant prose and footnotes you will actually read.",
    priceCents: 3200,
    format: "physical",
    category: "nonfiction",
    rating: 4.5,
    reviewCount: 57,
    inventoryCount: 3,
    pages: 412,
    publisher: "Harborlight",
    publishedYear: 2022,
    coverHue: 38,
  },
  {
    id: "book-005",
    slug: "letters-from-the-shelf",
    title: "Letters from the Shelf",
    author: "Shwe Yee Winn",
    description:
      "Curated correspondence between readers and booksellers, spanning decades. A love letter to the shop counter and the recommendations written on index cards.",
    priceCents: 2600,
    format: "physical",
    category: "literary",
    featured: true,
    rating: 4.9,
    reviewCount: 41,
    inventoryCount: 20,
    pages: 288,
    publisher: "Novella Editions",
    publishedYear: 2025,
    coverHue: 350,
  },
  {
    id: "book-006",
    slug: "tide-lines-digital",
    title: "Tide Lines",
    author: "Morgan Vale",
    description:
      "Poetry and prose at the shoreline. Instant download; links expire in 24 hours for your security.",
    priceCents: 1200,
    format: "digital",
    category: "literary",
    rating: 4.3,
    reviewCount: 33,
    coverHue: 195,
  },
  {
    id: "book-007",
    slug: "the-compass-room",
    title: "The Compass Room",
    author: "Felix Ortega",
    description:
      "A scholar inherits a study where every drawer contains a map to somewhere he has never been. Literary fiction with a puzzle at its heart.",
    priceCents: 2400,
    format: "physical",
    category: "fiction",
    rating: 4.2,
    reviewCount: 92,
    inventoryCount: 0,
    pages: 336,
    coverHue: 265,
  },
  {
    id: "book-008",
    slug: "small-rain",
    title: "Small Rain",
    author: "Priya Nand",
    description:
      "A gentle guide to reading slowly, one chapter per evening, with journal prompts and margins wide enough for your own notes.",
    priceCents: 1800,
    format: "physical",
    category: "nonfiction",
    rating: 4.7,
    reviewCount: 64,
    inventoryCount: 15,
    pages: 192,
    coverHue: 180,
  },
];
