import type { Book } from "./types";

export const newReleaseBooks: Book[] = [
  {
    id: "nr-001",
    slug: "grade-12-mathematics-old-questions",
    title:
      "ဒွါဒသမတန်း MATHEMATICS (၃)နှစ်စာ တက္ကသိုလ်ဝင်စာမေးပွဲ မေးခွန်းဟောင်း (၂၄)စုံနှင့် စံပြအဖြေများ",
    author: "Unknow Author",
    description:
      "Grade 12 mathematics—three years of university entrance old questions (24 sets) with model answers.",
    priceCents: 4500,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.5,
    reviewCount: 0,
    inventoryCount: 12,
    coverHue: 42,
    coverImageSrc: "/covers/new-releases/nr1-mathematics.webp",
    publishedYear: 2026,
  },
  {
    id: "nr-002",
    slug: "grade-12-english-old-questions",
    title: "ဒွါဒသမတန်း English Old Questions For Three Years (24) sets",
    author: "Unknow Author",
    description:
      "Grade 12 English—old entrance exam questions for 2024, 2025, and 2026 (24 sets).",
    priceCents: 4500,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.5,
    reviewCount: 0,
    inventoryCount: 12,
    coverHue: 330,
    coverImageSrc: "/covers/new-releases/nr2-english.webp",
    publishedYear: 2026,
  },
  {
    id: "nr-003",
    slug: "yin-kyay-lin-ma-38-mingala",
    title: "ယဉ်ကျေးလိမ္မာ ၃၈မင်္ဂလာ",
    author: "ဦးအားရွှေ",
    description: "Thirty-eight blessings of courtesy and refinement by U Aar Shwe.",
    priceCents: 3200,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.6,
    reviewCount: 0,
    inventoryCount: 10,
    coverHue: 350,
    coverImageSrc: "/covers/new-releases/nr3-yin-kyay-lin-ma.webp",
    publishedYear: 2026,
  },
  {
    id: "nr-004",
    slug: "shone-thwar-naing-aye-phyo-paing",
    title: "ရှုံးသွားရင်တောင် နိုင်နေမယ့်အလုပ် လုပ်ပါ",
    author: "Dr. Phyo Paing",
    description:
      "Notes on life and business—even when you lose, keep doing work that keeps you winning.",
    priceCents: 3800,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.7,
    reviewCount: 0,
    inventoryCount: 15,
    coverHue: 160,
    coverImageSrc: "/covers/new-releases/nr4-phyo-paing.webp",
    publishedYear: 2026,
  },
  {
    id: "nr-005",
    slug: "mi-mi-ko-ko-pyupyan",
    title: "မိမိကိုယ်ကိုပြုပြင်ခြင်း",
    author: "အရှင်စန္ဒိမာ (ရွှေဂန္ထဝင်)",
    description:
      "Self-improvement—ways of living and essays on success by Ashin Sandima (Shwe Gandawin).",
    priceCents: 3500,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.8,
    reviewCount: 0,
    inventoryCount: 14,
    coverHue: 210,
    coverImageSrc: "/covers/new-releases/nr5-self-improvement.webp",
    publishedYear: 2026,
  },
  {
    id: "nr-006",
    slug: "eternal-light-magazine-vol-15-5",
    title:
      "အသက် ၅၀ကျော်လျှင် သတိထားရမည့် ခါးရိုးကျဉ်းရောဂါ Eternal Light Magazine (Vol 15 No(5) 2026 April)",
    author: "Unknow Author",
    description:
      "Eternal Light Magazine Vol. 15 No. 5 (April 2026)—spinal stenosis awareness for readers over 50.",
    priceCents: 2800,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.4,
    reviewCount: 0,
    inventoryCount: 20,
    coverHue: 48,
    coverImageSrc: "/covers/new-releases/nr6-eternal-light.webp",
    publishedYear: 2026,
  },
  {
    id: "nr-007",
    slug: "lu-taing-ah-yone-tha-ma",
    title: "လူတိုင်း အရောင်းသမား",
    author: "ဒီပါ",
    description:
      "To Sell is Human—Burmese edition translated by Depa (Daniel H. Pink).",
    priceCents: 4200,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.6,
    reviewCount: 0,
    inventoryCount: 11,
    coverHue: 52,
    coverImageSrc: "/covers/new-releases/nr7-sell-human.webp",
    publishedYear: 2026,
  },
  {
    id: "nr-008",
    slug: "pyin-yin-hkin-ma-shi-pa",
    title: "ပျင်းရိခြင်းဆိုတာ မရှိပါ",
    author: "လူသာ",
    description:
      "Laziness Does Not Exist—Burmese translation by Lu Thar (Devon Price, Ph.D.).",
    priceCents: 4000,
    format: "physical",
    category: "nonfiction",
    collections: ["new-releases"],
    rating: 4.7,
    reviewCount: 0,
    inventoryCount: 13,
    coverHue: 130,
    coverImageSrc: "/covers/new-releases/nr8-laziness.webp",
    publishedYear: 2026,
  },
];
