import type { Book } from "./types";

export const preOrderBooks: Book[] = [
  {
    id: "pre-001",
    slug: "son-mat-myar-pre-order",
    title: "ဆုံမှတ်များ (Pre Order)",
    author: "မှူး",
    description: "Sally Rooney’s Normal People in Burmese—pre-order now. Ships when stock arrives.",
    priceCents: 2800,
    format: "physical",
    category: "fiction",
    preOrder: true,
    collections: ["pre-order"],
    rating: 4.5,
    reviewCount: 0,
    inventoryCount: 0,
    coverHue: 195,
    coverImageSrc: "/covers/pre-order/son-mat-myar.webp",
    publishedYear: 2026,
  },
  {
    id: "pre-002",
    slug: "nyan-pyin-hsan-pre-order",
    title: "ဉာဏ်ပညာနဲ့ ဆင်ယင်ထားတဲ့ အလှတရား (Pre Order)",
    author: "စုမြတ်ချစ်, စူးရှမေ, …",
    description:
      "Beauty with the Brain—four voices on intellect and grace. Pre-order the physical edition.",
    priceCents: 3200,
    format: "physical",
    category: "nonfiction",
    preOrder: true,
    collections: ["pre-order"],
    rating: 4.6,
    reviewCount: 0,
    inventoryCount: 0,
    coverHue: 280,
    coverImageSrc: "/covers/pre-order/nyan-pyin-hsan.webp",
    publishedYear: 2026,
  },
  {
    id: "pre-003",
    slug: "lok-dan-pre-order",
    title: "လောကဓံကို ဘယ်လိုရင်ဆိုင်မလဲ (Pre Order)",
    author: "မင်းထက်ဟန်",
    description:
      "How to face the weight of the world—pre-order this physical title before release.",
    priceCents: 2600,
    format: "physical",
    category: "nonfiction",
    preOrder: true,
    collections: ["pre-order"],
    rating: 4.4,
    reviewCount: 0,
    inventoryCount: 0,
    coverHue: 12,
    coverImageSrc: "/covers/pre-order/lok-dan.webp",
    publishedYear: 2026,
  },
  {
    id: "pre-004",
    slug: "a-yay-ma-pa-ta-pre-order",
    title: "အရေးမပါတာတွေကို…မခံစားတော့ပါ (Pre Order)",
    author: "ဖြိုးမင်းသန့်",
    description:
      "Stop letting everything affect you—Burmese edition by Phyo Min Thant. Pre-order now.",
    priceCents: 2400,
    format: "physical",
    category: "nonfiction",
    preOrder: true,
    collections: ["pre-order"],
    rating: 4.5,
    reviewCount: 0,
    inventoryCount: 0,
    coverHue: 38,
    coverImageSrc: "/covers/pre-order/a-yay-ma-pa-ta.webp",
    publishedYear: 2026,
  },
  {
    id: "pre-005",
    slug: "htet-naing-psychology-pre-order",
    title: "မထားခဲ့ခင်ကတည်းက ထွက်ပြေးချင်နေတယ် (Pre Order)",
    author: "Min Htet Naing",
    description:
      "Attachment theory and psychology—pre-order Min Htet Naing’s latest physical book.",
    priceCents: 3000,
    format: "physical",
    category: "nonfiction",
    preOrder: true,
    collections: ["pre-order"],
    rating: 4.7,
    reviewCount: 0,
    inventoryCount: 0,
    coverHue: 145,
    coverImageSrc: "/covers/pre-order/htet-naing-psychology.webp",
    publishedYear: 2026,
  },
];
